import type { Metadata } from "next";
import LegalPageShell from "@/components/legal/LegalPageShell";
import { LegalSection, LegalCallout, LegalList, LegalContact } from "@/components/legal/LegalSection";

export const metadata: Metadata = {
  title: "Privacy Policy | DoonMeet",
  description:
    "Learn how DoonMeet collects, uses and protects your personal data, including location, chat and profile information.",
};

const LAST_UPDATED = "17 July 2026";

const TOC = [
  { id: "introduction", number: "01", label: "Introduction" },
  { id: "information-we-collect", number: "02", label: "Information we collect" },
  { id: "how-we-use", number: "03", label: "How we use it" },
  { id: "location-data", number: "04", label: "Location & the live map" },
  { id: "cookies", number: "05", label: "Cookies & sessions" },
  { id: "sharing", number: "06", label: "How we share data" },
  { id: "payments", number: "07", label: "Payments (upcoming)" },
  { id: "retention", number: "08", label: "Data retention" },
  { id: "your-rights", number: "09", label: "Your rights & choices" },
  { id: "children", number: "10", label: "Age requirement" },
  { id: "security", number: "11", label: "Security" },
  { id: "third-party-links", number: "12", label: "Third-party links" },
  { id: "changes", number: "13", label: "Changes to this policy" },
  { id: "grievance", number: "14", label: "Grievance officer" },
  { id: "contact", number: "15", label: "Contact us" },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPageShell
      active="privacy"
      title="Privacy Policy"
      description="This explains what information DoonMeet collects, why we collect it, and the choices you have — including around location sharing and your public chat activity."
      lastUpdated={LAST_UPDATED}
      toc={TOC}
    >
      <LegalSection id="introduction" number="01" title="Introduction">
        <p>
          DoonMeet (&quot;DoonMeet&quot;, &quot;we&quot;, &quot;us&quot;) operates{" "}
          <strong>doonmeet.in</strong>, a local social platform for Dehradun that lets people
          discover events, join communities, chat with each other, and see who&apos;s nearby on a
          live map. This Privacy Policy applies to everyone who visits or creates an account on
          DoonMeet, including guest users.
        </p>
        <p>
          By using DoonMeet, you agree to the collection and use of information as described here.
          If you don&apos;t agree, please don&apos;t use the platform.
        </p>
      </LegalSection>

      <LegalSection id="information-we-collect" number="02" title="Information we collect">
        <p>We collect information in three ways: what you give us, what you generate by using the app, and what your device shares automatically.</p>
        <p className="font-semibold text-[rgb(var(--text))]">Information you provide</p>
        <LegalList
          items={[
            <>Name, email address and password when you sign up.</>,
            <>Your Google name, email and profile photo, if you sign in with Google.</>,
            <>Profile details you choose to add — bio, gender, area/address, interests, phone number and a profile photo.</>,
            <>A display name only, if you join as a guest (no email or password required).</>,
          ]}
        />
        <p className="font-semibold text-[rgb(var(--text))]">Information generated by using DoonMeet</p>
        <LegalList
          items={[
            <>Messages you send in the public chat, direct messages, and event comments.</>,
            <>Events and communities you create, join or interact with.</>,
            <>Your precise GPS coordinates and an optional label, only when you actively check in on the live map.</>,
            <>Basic activity data — last seen time, login timestamps, and device/browser type for security and rate-limiting.</>,
          ]}
        />
        <p className="font-semibold text-[rgb(var(--text))]">Information from your device</p>
        <LegalList
          items={[
            <>IP address, used for rate limiting and abuse prevention.</>,
            <>Standard browser/device information sent with every web request.</>,
          ]}
        />
      </LegalSection>

      <LegalSection id="how-we-use" number="03" title="How we use your information">
        <LegalList
          items={[
            <>To create and secure your account, and to keep guest sessions time-limited.</>,
            <>To operate core features: the live map, public chat, direct messages, communities and events.</>,
            <>To send account emails — verification links, password resets, and important service notices.</>,
            <>To show your public profile to other users, respecting the privacy toggles you&apos;ve set.</>,
            <>To detect spam, abuse, and rate-limit violations, and to enforce our Terms of Service.</>,
            <>To improve the product — understanding which features people actually use.</>,
          ]}
        />
        <p>We do not use your data to run third-party advertising, and we do not sell your personal information to anyone.</p>
      </LegalSection>

      <LegalSection id="location-data" number="04" title="Location data & the live map">
        <p>
          DoonMeet&apos;s live map is <strong>fully opt-in</strong>. We only access your device
          location when you tap &quot;Check in,&quot; and nothing is shared until you do.
        </p>
        <LegalList
          items={[
            <>When you check in, your coordinates and any label you add (e.g. &quot;At Clock Tower&quot;) become visible to other users on the map, alongside your name and avatar.</>,
            <>You can hide yourself from the map at any time without deleting your check-in, or remove your location entirely.</>,
            <>We store only your latest check-in — we do not build a history or timeline of your movements.</>,
            <>Guest accounts cannot check in or appear on the map.</>,
          ]}
        />
        <LegalCallout tone="accent" title="A safety note, not just a privacy one">
          <p>
            Because the map shows your real, current location to other users, please use good
            judgement — check in at public spots rather than your home, and use the visibility
            and label controls to share only what you&apos;re comfortable with.
          </p>
        </LegalCallout>
      </LegalSection>

      <LegalSection id="cookies" number="05" title="Cookies & sessions">
        <p>
          We use essential, first-party cookies to keep you signed in — an access token and a
          refresh token, both httpOnly and not readable by scripts. We don&apos;t use third-party
          advertising or tracking cookies. Signing out, or letting a guest session expire, clears
          these cookies.
        </p>
      </LegalSection>

      <LegalSection id="sharing" number="06" title="How we share your information">
        <p>We do not sell your data. We share information only in these limited situations:</p>
        <LegalList
          items={[
            <><strong>Service providers</strong> we rely on to run DoonMeet — for example Cloudinary (image hosting for avatars and event banners) and our email provider (account and security emails). They only receive what&apos;s needed to perform their function.</>,
            <><strong>Google</strong>, if you choose to sign in with Google — we verify your identity with Google&apos;s servers but don&apos;t receive your Google password.</>,
            <><strong>Other users</strong>, limited to your public profile, chat messages, and map check-in, and only according to the visibility and privacy settings you&apos;ve chosen.</>,
            <><strong>Law enforcement or regulators</strong>, only where we&apos;re legally required to disclose information, or to protect the safety of our users or the public.</>,
            <><strong>A future owner</strong>, in the event of a merger, acquisition, or sale of DoonMeet&apos;s assets — you&apos;d be notified of any such change and of any change to this policy.</>,
          ]}
        />
      </LegalSection>

      <LegalSection id="payments" number="07" title="Payments (upcoming features)">
        <p>
          DoonMeet is currently free to use. We plan to introduce paid features in the future
          (such as premium account features or paid event listings). When that happens:
        </p>
        <LegalList
          items={[
            <>Payments will be processed by a licensed third-party payment gateway — we do not, and will not, store your full card, UPI or bank details on our own servers.</>,
            <>We&apos;ll only retain what&apos;s needed for receipts, support, and fraud prevention — such as a transaction ID, amount, and status.</>,
            <>This policy will be updated before any paid feature goes live, and our{" "}
              <a href="/refund-policy" className="font-semibold underline" style={{ color: "rgb(var(--primary))" }}>
                Refund &amp; Cancellation Policy
              </a>{" "}
              will explain how charges and cancellations work.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection id="retention" number="08" title="Data retention">
        <LegalList
          items={[
            <>Regular account data is kept for as long as your account is active.</>,
            <>Guest accounts and their messages are tied to a 24-hour session and are not intended for long-term storage.</>,
            <>Password reset and email verification tokens expire automatically (1 hour and 24 hours respectively) and are deleted once used.</>,
            <>Notifications are automatically deleted after 30 days.</>,
            <>If you delete your account, we remove your profile, messages, and location data within a reasonable period, except where we&apos;re required to retain limited records for legal, security, or fraud-prevention purposes.</>,
          ]}
        />
      </LegalSection>

      <LegalSection id="your-rights" number="09" title="Your rights & choices">
        <p>You&apos;re always in control of your data on DoonMeet:</p>
        <LegalList
          items={[
            <><strong>Access &amp; correction</strong> — view and edit your profile at any time from your account settings.</>,
            <><strong>Privacy toggles</strong> — choose whether your email, phone, gender, address and interests are visible to other users.</>,
            <><strong>Location control</strong> — hide yourself from the map or remove your check-in entirely, whenever you like.</>,
            <><strong>Deletion</strong> — request full deletion of your account and associated data by contacting us.</>,
            <><strong>Portability</strong> — request a copy of the personal data we hold about you.</>,
          ]}
        />
        <p>
          If you&apos;re in India, these rights are consistent with the Digital Personal Data
          Protection Act, 2023. To exercise any of them, contact us using the details at the
          bottom of this page.
        </p>
      </LegalSection>

      <LegalSection id="children" number="10" title="Age requirement">
        <LegalCallout tone="danger" title="DoonMeet is for adults — 18 years and older">
          <p>
            Because DoonMeet involves real-time location sharing and public chat with strangers,
            we require all users to be at least 18 years old. We do not knowingly allow anyone
            under 18 to create an account or use guest access. If we become aware that someone
            under 18 is using DoonMeet, we&apos;ll remove the account and associated data.
          </p>
        </LegalCallout>
      </LegalSection>

      <LegalSection id="security" number="11" title="Security">
        <p>
          We take reasonable technical and organisational measures to protect your data,
          including password hashing (bcrypt), httpOnly session cookies, rate limiting on
          sensitive endpoints, and input sanitisation to prevent common web attacks. No online
          service can guarantee absolute security, but we work to keep DoonMeet as safe as
          reasonably possible and will notify affected users if a breach materially impacts their
          data.
        </p>
      </LegalSection>

      <LegalSection id="third-party-links" number="12" title="Third-party links">
        <p>
          DoonMeet may link out to third-party sites (such as an event organiser&apos;s Instagram,
          or a place&apos;s listing). We aren&apos;t responsible for the privacy practices of
          those sites — please review their own policies before sharing information with them.
        </p>
      </LegalSection>

      <LegalSection id="changes" number="13" title="Changes to this policy">
        <p>
          We may update this Privacy Policy as DoonMeet grows — for example, when we introduce
          paid features. We&apos;ll update the &quot;Last updated&quot; date at the top of this
          page, and for significant changes we&apos;ll make a reasonable effort to notify you (for
          example, by email or an in-app notice).
        </p>
      </LegalSection>

      <LegalSection id="grievance" number="14" title="Grievance officer">
        <p>
          In accordance with the Information Technology Act, 2000 and the rules made thereunder,
          the Grievance Officer for DoonMeet can be reached at the contact details below for any
          complaints or concerns regarding content or privacy on the platform.
        </p>
        <p>
          <strong>Name:</strong> Ravish Bisht
          <br />
          <strong>Email:</strong> cykoravish@gmail.com
          <br />
          <strong>Location:</strong> Dehradun, Uttarakhand, India
        </p>
      </LegalSection>

      <LegalSection id="contact" number="15" title="Contact us">
        <p>
          Questions about this Privacy Policy, or want to exercise any of your data rights? Reach
          out any time.
        </p>
      </LegalSection>

      <LegalContact />
    </LegalPageShell>
  );
}